(function () {
  var NEWLINE = "\n";
  var SPACE = " ";
  var PAUSE = "";

  window.songData = {
    bpm: 120,
    offset: 0.1,
    lyrics: [
      [
        [2.5, PAUSE],
        [0.5, "ca"],
        [0.5, "reer"],
        [0, SPACE],
        [0.5, "boy"],
        [4, NEWLINE],
        [0.5, "work"],
        [0.5, PAUSE],
        [0.5, "ing"],
        [0, SPACE],
        [1, "ove"],
        [0.5, "r"],
        [2, "time"],
      ],

      [
        [5.5, PAUSE],
        [0.5, "ca"],
        [0.5, "reer"],
        [0, SPACE],
        [0.5, "boy"],
        [4, NEWLINE],
        [0.25, "one"],
        [0.75, SPACE],
        [0.25, "thing"],
        [0.25, SPACE],
        [0.25, "on"],
        [0.5, SPACE],
        [0.25, "my"],
        [0.25, SPACE],
        [1.75, "mind"],
      ],

      [
        [6, PAUSE],
        [0.25, "cheap"],
        [0.25, SPACE],
        [0.5, "office"],
        [0.25, SPACE],
        [0.75, "coffee"],
        [3, NEWLINE],
        [0.25, "is"],
        [0.25, SPACE],
        [0.25, "pump"],
        [0.5, PAUSE],
        [0.25, "ing"],
        [0.25, SPACE],
        [0.25, "through"],
        [0.5, SPACE],
        [0.25, "my"],
        [0.25, SPACE],
        [2, "veins"],
      ],

      [
        [5.5, PAUSE],
        [0.25, "I"],
        [0, SPACE],
        [0.25, "work"],
        [0.25, SPACE],
        [0.25, "for"],
        [0.25, SPACE],
        [0.25, "the"],
        [0.25, SPACE],
        [0.25, "man"],
        [0.25, SPACE],
        [0.5, "yeah"],
        [2, NEWLINE],
        [0.25, "but"],
        [0.25, SPACE],
        [0.25, "you"],
        [0.25, SPACE],
        [0.25, "know"],
        [0.5, SPACE],
        [0.25, "I"],
        [0.25, SPACE],
        [0.25, "love"],
        [0.75, SPACE],
        [0.25, "the"],
        [0.25, SPACE],
        [3, "chase"],
      ],

      [
        [3, PAUSE],
        [0.25, "I"],
        [0, SPACE],
        [0.25, "can"],
        [0, SPACE],
        [0.5, "never"],
        [0, SPACE],
        [0.25, "fight"],
        [0.5, SPACE],
        [0.25, "the"],
        [0.25, SPACE],
        [0.5, "feeling"],
        [1.25, NEWLINE],
        [0.25, "I"],
        [0.25, SPACE],
        [0.25, "stay"],
        [0.25, SPACE],
        [0.25, "up"],
        [0.25, SPACE],
        [0.25, "all"],
        [0.5, SPACE],
        [0.25, "night"],
      ],
    ],
  };
})();
